version: "3"
services:
  mysql:
    image: "mysql:5.7"
    container_name: my-mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horses
      MYSQL_USER: horse
      MYSQL_PASSWORD: gohorse
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - hosrse-host


volumes:
  db-data:

networks:
  hosrse-host:
    driver: bridge